# Generated by Django 5.0.7 on 2024-08-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_is_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="count_views",
            field=models.IntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Количество просмотров",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="products/image",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="is_publication",
            field=models.BooleanField(default=False, verbose_name="Создать?"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Индефикатор"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(
                help_text="Введите заголовок", max_length=50, verbose_name="Заголовок"
            ),
        ),
    ]
