# Generated by Django 5.0.7 on 2024-08-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_count_views_alter_blog_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                help_text="Загрузите изображение",
                upload_to="products/image",
                verbose_name="Изображение",
            ),
        ),
    ]
