# Generated by Django 5.0.7 on 2024-08-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                max_length=150, null=True, unique=True, verbose_name="Иденфикатор"
            ),
        ),
    ]
