# Generated by Django 4.2.2 on 2024-09-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("can_change_description", "Can change description of product"),
                    ("can_change_category", "Can change category of product"),
                    ("can_cancel__is_published", "Can cancel is_published"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="ВОпубликовано?", verbose_name="Опубликовано"
            ),
        ),
    ]
